# https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html
# Parameters INPUT, KMS_KEY_ID, and BUCKET_NAME are injected from the CloudFormation template.
version: 0.2
env:
  variables:
    OUTPUT: "output.cfn.yml"
    SBT_VERSION: "1.5.5"
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo `pwd`
      - sbt assembly
      - |
        if [ "X$KMS_KEY_ID" = "X" ]; then
          aws cloudformation package --template-file $INPUT_TEMPLATE --s3-bucket $BUCKET_NAME --output-template-file $OUTPUT
        else
          aws cloudformation package --template-file $INPUT_TEMPLATE --s3-bucket $BUCKET_NAME --kms-key-id $KMS_KEY_ID --output-template-file $OUTPUT
        fi
artifacts:
  type: zip
  files:
    - $OUTPUT
    - $LAMBDA_CONF
  base-directory: .
