AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Resources:
  CreateObject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.malliina.lambda.s3.S3Handler
      Runtime: java8
      Timeout: 60
      Policies: AWSLambdaExecute
      Events:
        CreateObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*

  SrcBucket:
    Type: AWS::S3::Bucket
