AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Parameters:

  ExampleKey:
    Type: String
    Description: Example key
    MinLength: 1
    MaxLength: 256

Resources:

  CreateObject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.malliina.lambda.s3.S3Handler
      Runtime: java8
      CodeUri: ./function.jar
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          EXAMPLE_KEY: !Ref ExampleKey
      Policies: AWSLambdaExecute
      Events:
        CreateObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*

  SrcBucket:
    Type: AWS::S3::Bucket
