version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `pwd`
      - sbt sbtVersion
      - sbt "project lambda" assembly
      - unzip lambda/function.jar -d jartarget
artifacts:
  files:
    - '**/*'
  base-directory: jartarget
