# https://github.com/aws/aws-cdk/issues/11025#issuecomment-1207476335
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `pwd`
      - npm install -g aws-cdk@$CDK_VERSION
      - npm install -g cdk-assets@$CDK_VERSION
  pre-build:
    commands:
      - cdk synth $LAMBDA_STACK -o target
  build:
    commands:
      - cdk-assets -p target/$LAMBDA_STACK.assets.json publish
artifacts:
  files:
    - $OUTPUT
  base-directory: target
