# https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html
# Parameters KMS_KEY_ID and BUCKET_NAME are injected from the CloudFormation template.
# Use input.cfn.yml to create an AWS API Gateway API proxy to your Lambda.
# Use input-slim.cfn.yml to create a Lambda without any API Gateway integration.
version: 0.2
env:
  variables:
    OUTPUT: "LambdaStack.template.json"
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo `pwd`
      - npm install -g aws-cdk
  build:
    commands:
      - cdk synth LambdaStack -o target
artifacts:
  files:
    - $OUTPUT
  base-directory: target
