version: 0.2
env:
  variables:
    OUTPUT: "LambdaStack.template.json"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `pwd`
      - npm install -g aws-cdk@$CDK_VERSION
  build:
    commands:
      - cdk synth LambdaStack -o target
artifacts:
  files:
    - $OUTPUT
  base-directory: target
