version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `pwd`
      - npm install -g aws-cdk@$CDK_VERSION
  build:
    commands:
      - cdk synth $LAMBDA_STACK -o target
artifacts:
  files:
    - $OUTPUT
  base-directory: target
