name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.11"
      - name: Install AWS CDK
        run: |
          sudo npm install -g aws-cdk@2.65.0
          cdk --version
      - name: Run tests
        run: sbt test
#      - name: Validate CDK
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: 'eu-north-1'
#        run: |
#          cdk synth
